=pod

=head1 Markov Bot Projects (Quickbot)

Markov bot instead of ELIZA clone (easier, faster to create)

=for html <img src="mascot.jpg" alt="quickbot mascot">

=head2 Themes

=head3 Lightning/Balalaika/Yandere Waifubot

- Lightning:

  - https://finalfantasy.fandom.com/wiki/Lightning_Returns:_Final_Fantasy_XIII_script

  - http://ffxiiitranscript.blogspot.com/

- Balalaika:

  - https://www.opensubtitles.org/en/search2/sublanguageid-all/moviename-black+lagoon+

  - https://www.quotes.net/movies/black_lagoon_100757

  - https://tvtropes.org/pmwiki/pmwiki.php/Quotes/BlackLagoon

  - https://www.imdb.com/title/tt0962826/quotes/

  - https://duckduckgo.com/?q=black+lagoon+balalaika+quotes+imdb&t=ffab&ia=web

- Yandere:

  - yandere ASMR scripts(?)

=head3 Me/My Rubber Ducky

- My discord logs

- My writing

- My quotes.org file

- Douglas Adams books

- Zero Punctuation transcriptions

- Izaya Orihara quotes

- Hazama quotes

- Terumi quotes

- n-gate

=head3 HN Bullshit

- Hackernews comments

=head2 TODOs

- specify how input files work (no punctuation, lines of sentences)

- discuss why interact() only does single-word input

=head2 Options

-h: show help

-t: train only (outputting to "weights.json" if the output file is not specified)

-r: run only (using "weights.json" if the weight file is not specified) - read from stdin

-o: specify output file

-w: specify weight file

-u: "unweighted" training; weights only contain distinct words, with no information about how often the occur

-l: specify minimum response length

=head2 Activation

Right now, quickbot I<only> handles single-word activation functions, and only ever will, as far as I can see. 
Why? 
Because there're a million ways to run a markov bot, and I don't want to handle all of them.
Use another script that munges the incoming message and pipes in or something. 
It'll be easier.
In the meantime, here are some ways of running it (IRC-style) that I though of:

=over

=item Use the last word in the input

=item Use the first/last word in the input that's in the vocab

=item Use a random word from the input that's in the vocab

=item Use a word that's in vocab and has the most associated words

=item Do multiple sentences using each word in vocab

=back

=cut
